### ISSUE TITLE
Some solutions to setup issues

### ISSUE THREAD

**Issue by dudo24** [Nerixyz/current-song-overlay#18]
I forked the repository and made in Wiki tab a little guide how I overcame issues with the setup. So check it out if you run into some problems, it might have a solution for you.

[direct link to my fork wiki](https://github.com/dudo24/current-song-overlay/wiki)

**Comment by Nerixyz** [comment]
Thanks for the writeup!

I'll try to include a few possible errors in the readme soon.

One thing I didn't mention was the powershell execution-policy issue. 
It's yet another reason why I'm trying to have everything included in a single executable in the next version that does service handling on its own.

**Comment by dudo24** [comment]
I am glad I could contribute a little. Keep up the good work, I am looking forward to the next version :)
