### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by JeremyStarTM** [Nerixyz/current-song-overlay#23]
Can Linux be supported too?

**Comment by Nerixyz** [comment]
Linux should be supported _but_ you need to run/build it from source.

This should boil down to running `cd client && npm i && npm run build` (to build the overlay) and `export NON_BUILD_ENV = 1 && deno run --allow-read --allow-net --allow-env --allow-write --unstable server/src/index.ts` (in the project root, see [scripts/final/start.bat](https://github.com/Nerixyz/current-song-overlay/blob/master/scripts/final/start.bat))

Setting `NON_BUILD_ENV` results in the server serving client files from `client/public`.
